[package]
name = "evergreen-ttl"
version = "0.1.0"
edition = "2021"
authors = ["Evergreen Contributors <evergreen@stellar.org>"]
description = "Soroban contract storage TTL extension helpers"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/stellar/evergreen"

[dependencies]
soroban-sdk = "21.2.0"

[dev-dependencies]
soroban-sdk = { version = "21.2.0", features = ["testutils"] }
